server:
  port: 9061
spring:
  application:
    name: tensquare-base
  datasource:
    username: root
    password:  123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.236.129:33306/tensquare_base?characterEncoding=utf-8
  jpa:
    database: mysql
    show-sql: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/