server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    username: root
    password:  123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.1:3306/tensquare_base?characterEncoding=utf-8
  jpa:
    database: mysql
    show-sql: true
