server:
  port: 9010
spring:
  application:
    name: tensquare-friend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.236.129:33306/tensquare_friend?characterEncoding=UTF8
    username: root
    password: 123456
  redis:
    host: 192.168.236.129
  jpa:
    show-sql: true
    database: mysql
jwt:
  config:
    key: fuli
eureka:
  client:
    service-url: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true