server: 
  port: 9008
spring: 
  application:  
    name: user-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.236.129:33306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.236.129
  rabbitmq:
    host: 192.168.236.129
jwt:
  config:
    key: fuli
    ttl: 360000